[general]
import = ["vague.toml"]

[window]
decorations = "None"
startup_mode = "Fullscreen"
option_as_alt = "Both"

[font]
normal = { family = "JetBrainsMonoNL NFM", style = "Regular" }

[cursor]
style = { shape = "Block", blinking = "Always" }
blink_interval = 300
blink_timeout = 0
